version = 0.1

[default.deploy.parameters]
stack_name = "live2d-aws-backend"
resolve_s3 = true
s3_prefix = "live2d-aws-backend"
region = "us-west-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM CAPABILITY_AUTO_EXPAND"
disable_rollback = true
parameter_overrides = "Env=\"dev\""
image_repositories = []
