#!/usr/bin/env python3
"""
Simple AWS Deployment Script
Fixed version that handles the issues encountered in the automated setup
"""

import os
import sys
import subprocess
import json
from pathlib import Path

def main():
    print("=" * 60)
    print("Simple AWS Knowledge Base Deployment")
    print("=" * 60)
    
    # Step 1: Check if we're in the right directory
    if not Path("backend/template-enhanced.yml").exists():
        print("Error: template-enhanced.yml not found in backend directory")
        print("Please run this script from the LLM-Live2D-Desktop-Assitant-main directory")
        return 1
    
    # Step 2: Deploy using the existing template (not enhanced)
    print("Step 1: Deploying basic infrastructure...")
    print("Using existing template.yml with RAG infrastructure enabled")
    
    try:
        # Change to backend directory
        os.chdir("backend")
        
        # Deploy using existing template with RAG enabled
        cmd = [
            "sam", "deploy",
            "--template-file", "template.yml",
            "--stack-name", "live2d-aws-backend",
            "--parameter-overrides", "Env=dev", "EnableRagInfra=true",
            "--capabilities", "CAPABILITY_IAM", "CAPABILITY_NAMED_IAM",
            "--region", "us-west-2"
        ]
        
        print(f"Running: {' '.join(cmd)}")
        result = subprocess.run(cmd, capture_output=True, text=True)
        
        if result.returncode != 0:
            print(f"SAM deploy failed:")
            print(f"STDOUT: {result.stdout}")
            print(f"STDERR: {result.stderr}")
            return 1
        
        print("✅ Infrastructure deployed successfully")
        print(result.stdout)
        
        # Go back to parent directory
        os.chdir("..")
        
    except Exception as e:
        print(f"Deployment error: {e}")
        return 1
    
    # Step 2: Get stack outputs
    print("\nStep 2: Getting deployment information...")
    try:
        cmd = ["aws", "cloudformation", "describe-stacks", "--stack-name", "live2d-aws-backend", "--region", "us-west-2"]
        result = subprocess.run(cmd, capture_output=True, text=True)
        
        if result.returncode != 0:
            print(f"Failed to get stack info: {result.stderr}")
            return 1
        
        stack_data = json.loads(result.stdout)
        outputs = {}
        
        for output in stack_data['Stacks'][0].get('Outputs', []):
            outputs[output['OutputKey']] = output['OutputValue']
        
        print("Stack outputs:")
        for key, value in outputs.items():
            print(f"  {key}: {value}")
        
        # Step 3: Create environment file
        bucket_name = outputs.get('DocumentsBucketName', '')
        http_base = outputs.get('HttpBase', '')
        ws_url = outputs.get('WSUrl', '')
        opensearch_endpoint = outputs.get('OpenSearchDomainEndpoint', '')
        role_arn = outputs.get('BedrockKBRoleArn', '')
        
        env_content = f"""# AWS Configuration - Generated by simple_aws_deploy.py
AWS_REGION=us-west-2
DOCUMENTS_BUCKET_NAME={bucket_name}
HTTP_API_BASE={http_base}
WEBSOCKET_URL={ws_url}
OPENSEARCH_ENDPOINT={opensearch_endpoint}
BEDROCK_KB_ROLE_ARN={role_arn}

# RAG Configuration
RAG_ENABLED=true
RAG_MODE=hybrid
PREFER_AWS_RAG=true
RAG_MAX_RESULTS=5
RAG_SCORE_THRESHOLD=0.5

# Note: AWS_KNOWLEDGE_BASE_ID will be added after manual KB creation
# AWS_KNOWLEDGE_BASE_ID=your-kb-id-here
"""
        
        with open(".env.aws", "w") as f:
            f.write(env_content)
        
        print(f"\n✅ Environment file created: .env.aws")
        
    except Exception as e:
        print(f"Error getting stack outputs: {e}")
        return 1
    
    # Step 3: Instructions for manual Knowledge Base creation
    print("\n" + "=" * 60)
    print("NEXT STEPS - Manual Knowledge Base Creation")
    print("=" * 60)
    print()
    print("Your AWS infrastructure is deployed! Now you need to create the Knowledge Base manually:")
    print()
    print("1. Go to AWS Bedrock Console:")
    print("   https://console.aws.amazon.com/bedrock/")
    print()
    print("2. Navigate to 'Knowledge Bases' → 'Create Knowledge Base'")
    print()
    print("3. Use these settings:")
    print(f"   - Name: live2d-manufacturing-kb")
    print(f"   - IAM Role: {role_arn}")
    print(f"   - S3 Data Source: s3://{bucket_name}/manufacturing/")
    print(f"   - OpenSearch Domain: {opensearch_endpoint}")
    print("   - Embedding Model: amazon.titan-embed-text-v1")
    print("   - Chunking: Fixed Size, 300 tokens, 20% overlap")
    print()
    print("4. After creating the Knowledge Base, update .env.aws with the KB ID:")
    print("   AWS_KNOWLEDGE_BASE_ID=your-actual-kb-id")
    print()
    print("5. Copy the environment file:")
    print("   copy .env.aws .env")
    print()
    print("6. Upload sample documents:")
    print(f"   aws s3 cp rag_documents\\ s3://{bucket_name}/manufacturing/ --recursive")
    print()
    print("7. Test the integration:")
    print("   python run_enhanced_server.py")
    print()
    
    return 0

if __name__ == "__main__":
    sys.exit(main())